languageCode = "en-us"
title = "gjesse.github.io"
baseURL = "https://gjesse.github.io/"

theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/gjesse\" target=\"_blank\">Twitter</a>"
#disqusShortname = "shortname"
#googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["jesse hodges", "software", "kotlin"]
author = "Jesse Hodges"
sharingicons = true

[params.highlight]
style = "solarized-light"
languages = ["kotlin"]

[[params.social]]
url = "https://github.com/gjesse"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/gjesse"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/gjesse"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

